use crate::context::Context;
use crate::error::{Error, Result};
use crate::syntax::Syntax;
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// A single template entry in the manifest.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct TemplateEntry {
    /// Path to the template source file (in the Nix store).
    pub source: PathBuf,

    /// Target path where the rendered output is written.
    pub target: PathBuf,

    /// File permissions (octal string like "0600").
    #[serde(default = "default_mode")]
    pub mode: String,

    /// Optional owner (user name or uid).
    #[serde(default)]
    pub owner: String,

    /// Optional group.
    #[serde(default)]
    pub group: String,

    /// Variable sources for this template.
    #[serde(default)]
    pub context: Context,
}

fn default_mode() -> String {
    "0600".into()
}

/// The full rendering manifest generated by the Nix module.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct Manifest {
    /// Custom syntax configuration (shared across all templates).
    #[serde(default)]
    pub syntax: Syntax,

    /// Named template entries.
    pub templates: BTreeMap<String, TemplateEntry>,
}

impl Manifest {
    /// Load a manifest from a JSON file.
    pub fn load(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path).map_err(|e| Error::ReadFile {
            path: path.to_path_buf(),
            source: e,
        })?;
        serde_json::from_str(&content).map_err(|e| Error::ParseManifest {
            path: path.to_path_buf(),
            source: e,
        })
    }
}
